twig:
    file_name_pattern: '*.twig'

    globals:
        # the value is the service's id
        current_ruestzeit_service: '@App\Generator\CurrentRuestzeitGenerator'
        privacyagreement_url: '%env(PRIVACYAGREEMENT_URL)%'

when@test:
    twig:
        strict_variables: true

