version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://symfony:symfony@database:3306/symfony?serverVersion=mariadb-10.6.15"
      MAILER_DSN: "smtp://localhost:1025"
    ports:
      - "8000:8000"

  database:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: symfony
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db-data: